[build]
  publish = "."
  functions = "netlify/functions"

[[edge_functions]]
  path = "/resources/top-investor-lists/*"
  function = "seo"

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/resources/top-investor-lists"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/resources/top-investor-lists/*"
  to = "/index.html"
  status = 200
