[build]
  publish = "."
  functions = "netlify/functions"

[[edge_functions]]
  path = "/resources/top-investor-lists/*"
  function = "seo"

[[edge_functions]]
  path = "/*"
  function = "seo"

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/resources/top-investor-lists/*"
  to = "/.netlify/functions/view-page"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

# Serve favicon from favicons.ico if that's the file present
[[redirects]]
  from = "/favicon.ico"
  to = "/favicons.ico"
  status = 200
